# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run:  echo Hello world! #swift build -v
    - name: Run tests
      run: | 
        xcodebuild clean test -project mini_project_swiftUI.xcodeproj -scheme mini_project_swiftUI -destination "platform=iOS Simulator,name=iPhone 11"
